index.js, lib/connector.js, lib/parameterized-sql.js, lib/sql.js, lib/transaction.js, test/automigrate.test.js, test/connectors/test-sql-connector.js, test/sql.test.js, test/transaction.test.js
/to @ritch @bajtos
This PR adds local transaction apis for relational DBs.
Connect to strongloop/loopback#109
=> Add transaction support

lib/sql.js, test/sql.test.js
/to @ritch
Connects to strongloop/loopback-datasource-juggler#464
=> Add hooks to sql based connectors

lib/sql.js, test/sql.test.js
Connect to strongloop/loopback-datasource-juggler#552
=> Add support for RegExp operator

lib/sql.js
- Do not coerce RegExp literal/objects into a string
=> Fix RegExp coercion

package.json
Connect to strongloop-internal/scrum-loopback#1063
=> Update deps to LB 3.0.0 RC

.gitignore, intl/de/messages.json, intl/es/messages.json, intl/fr/messages.json, intl/it/messages.json, intl/ja/messages.json, intl/ko/messages.json, intl/nl/messages.json, intl/pt/messages.json, intl/zh-Hans/messages.json, intl/zh-Hant/messages.json
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/1070
=> Add translated files

intl/es/messages.json, intl/ja/messages.json, intl/tr/messages.json, intl/zh-Hans/messages.json
https://github.com/strongloop-internal/scrum-loopback/issues/1097
=> Update translation files - round#2

index.js, lib/binary-packer.js, lib/model-key-composer.js, lib/utils.js, package.json, test/binary-packer.test.js, test/model-key-composer.test.js, test/transaction.test.js
Add `ModelKeyComposer` and `BinaryPacker` from kv-redis connector.
Connect to strongloop-internal/scrum-loopback#1128
See also the spike - strongloop/loopback-datasource-juggler#1129
@superkhau PTAL
=> KeyValue helpers

lib/json-string-packer.js, test/json-string-packer.test.js
@bajtos I have move JSON String Packer from [the pr of loopback-connector-kv-redis](https://github.com/strongloop/loopback-connector-kv-redis/pull/16)
If the pr is accepted, I'll send the other pr to loopback-connector-kv-redis to setup packer option.
=> Support JSONStringPacker

index.js
Hi @bajtos ,
I add the missing export variable `JSONStringPacker`.
=> Export JSONStringPacker

lib/sql.js
=> Add getDropColumns as a base function

lib/sql.js
Refactor discovery test cases
connect to https://github.com/strongloop/loopback-connector/issues/15
=> Refactor SQL discovery methods

lib/sql.js
Refactor discovery test cases
connect to https://github.com/strongloop/loopback-connector/issues/15
=> Refactor migration

lib/sql.js
Related code: https://github.com/strongloop/loopback-connector/blob/bba29f88f2a5cd23ae31d266c46f2a026503619e/lib/sql.js#L236
Each sql connector has its own check of `fields` and `indexes` exist method, then determine callback the result or not.
- None
=> Add checkFieldAndIndex

index.js, lib/binary-packer.js, lib/connector.js, lib/parameterized-sql.js, lib/sql.js, lib/transaction.js, lib/utils.js, package.json, test/automigrate.test.js, test/binary-packer.test.js, test/connectors/test-sql-connector.js, test/json-string-packer.test.js, test/smoke.test.js, test/sql.test.js, test/transaction.test.js
Upgrade deps and fix styles
- None
=> Update deps and fix styles

lib/connector.js
Add generateUniqueId prototype
- None
=> Add generateUniqueId prototype

lib/sql.js
Fix update Bug to report error when id is not found. 
An alternate solution to pr https://github.com/strongloop/loopback-connector/pull/97
connect to https://github.com/strongloop/loopback-datasource-juggler/issues/1185
tests in juggler: `updateOrCreate when forceId is true`
=> Fix update bug when id not found

lib/sql.js
Quick PR to fix a couple comment lines that badly formatted.
=> Fix comment lines

package.json
Use the latest minor release of loopback-datasource-juggler as a devDep.
- connected to #117
=> package: use loopback-datasource-juggler@3.12

index.js, lib/binary-packer.js, lib/connector.js, lib/json-string-packer.js, lib/model-key-composer.js, lib/parameterized-sql.js, lib/sql.js, lib/transaction.js, lib/utils.js, package.json, test/automigrate.test.js, test/binary-packer.test.js, test/connector.test.js, test/connectors/test-sql-connector.js, test/json-string-packer.test.js, test/model-key-composer.test.js, test/smoke.test.js, test/sql.test.js, test/transaction.test.js
- add `"author": "IBM Corp.",` in package.json so that `slt copyright` command can generate the right header
- Update copyrights year
=> Update copyrights year

index.js, lib/binary-packer.js, lib/connector.js, lib/json-string-packer.js, lib/model-key-composer.js, lib/parameterized-sql.js, lib/sql.js, lib/transaction.js, lib/utils.js, package.json, test/automigrate.test.js, test/binary-packer.test.js, test/connectors/test-sql-connector.js, test/json-string-packer.test.js, test/model-key-composer.test.js, test/smoke.test.js, test/sql.test.js, test/transaction.test.js
this repo's specific CI (not downstream ones) is currently failing due to a lint error so thought I'd use the chance to update to the latest `eslint` (and other dependencies)
- connect to <link_to_referenced_issue>
=> chore: update deps and fix lint violations

.github/workflows/continuous-integration.yaml
Connects to https://github.com/strongloop/loopback-next/issues/7054
Travis is still available for this repo. Add github actions just in case.
=> ci: add Github Actions

.github/codeql/codeql-config.yaml, .github/workflows/continuous-integration.yaml, .npmrc, .travis.yml, commitlint.config.js, package-lock.json, package.json
=> ci: update ci

README.md
=> docs: add ci badges

.github/workflows/continuous-integration.yaml
see: https://github.com/loopbackio/security/issues/27
=> ci: pin GitHub Actions Git hash

lib/connector.js
=> feat: return `multiInsertSupported` in `getMetadata`
