- lib/connector.js
Before this change, an attempt to save a model instance with a dynamic
property to a MySQL datasource crashed the application.
This commit fixes the implementation of `id(model, property)` to
correctly handle the case when the property is not described in the
model definition.
Connect strongloop/loopback-datasource-juggler#367
/to @raymondfeng please review
> Fix crash in `id(model, prop)`

- lib/sql.js
Allow 'before execute' hooks to modify the SQL query, parameters and options by modifying the context object.
> Enable Inversion of Control in connector hooks

- lib/transaction.js
Fixed typo in function `Transaction.begin`.
> Fixed typo

- lib/sql.js
connect to https://github.com/strongloop/loopback-datasource-juggler/issues/1171
connect to https://github.com/strongloop/loopback-connector-mysql/issues/230
connect to https://github.com/strongloop/loopback-connector-postgresql/issues/204
connect to https://github.com/strongloop/loopback-connector-mssql/issues/116
connect to https://github.com/strongloop/loopback-datasource-juggler/issues/1235
this pr is a prerequisite for:  https://github.com/strongloop/loopback-datasource-juggler/pull/1210
Unit test is included in:
'loopback-datasource-juggler/test/manipulation.test.js' section  'replaceOrCreate when forceId is true' which is being called from 'test/imported.test.js' from each sql connector. 
testedt with loopback-connectors:
> Fix replaceById to report an error when id not found

- lib/sql.js
Oracle uses `rowsAffected` instead of `affectedRows`, so that pr is to fix the test failure and fix the bug in question when we use replaceById when the id does not exist in db. 
Unit tests in Juggler.
> Fix replaceById for Oracle

- docs/sql-connector.md
- lib/connector.js
- lib/parameterized-sql.js
- lib/sql.js
PLEASE DO NOT MERGE YET.
This is to address #54.  Changes so far in this PR fix the problem with the `[ ]` characters and it now properly displays docs for base Connector and SQLConnector, but oddly the docs for `parameterized-sql.js` is now not there.  Also, the navigation seems to be pretty broken, and I don't really know why.
@0candy Perhaps you can shed some light?
connect to https://github.com/strongloop/loopback-connector/issues/54
> Fix API docs

- lib/transaction.js
- test/transaction.test.js
Original problem: strongloop/loopback-connector-postgresql#258
When calling beginTransaction, an error would occur saying Transaction is not active.
The cause of the problem is the connector (postgresql in this case) and juggler modules are pointing to a different version of connector.  It makes the check for the instance of Transaction failed. 
More details of explanation from @jannyHou can be found here: https://github.com/strongloop/loopback-connector-postgresql/pull/268#issuecomment-311388408
The fix (as suggested by @kjdelisle) is to have a softer check on the transaction.  i.e. to check for the existence of the `connector` and `connection` properties and `commit` & `rollback` function. 
connect to strongloop/loopback-connector-postgresql#258
- None …
> Fix Postgresql transaction

- lib/sql.js
- test/connectors/test-sql-connector.js
- test/transaction.test.js
When passing on a transaction object to connector.count(), it does not currently get passed on internally to the SQL `execute()` method, meaning that the count of the table outside the transaction will be counted and a wrong result will be returned.
This simple change fixes that. 
I will add a unit test for it in https://github.com/strongloop/loopback-connector-postgresql
- None
> Support transactions in count()

- lib/transaction.js
- package.json
As outlined in strongloop/loopback-datasource-juggler#1484, this simple PR is part two of moving the handling of transaction timeouts and ids from `loopback-datasource-juggler`'s [`TransactionMixin.beginTransaction()`](https://github.com/strongloop/loopback-datasource-juggler/blob/3b45c76d0fd3364c55a55720d685b5596fb578d1/lib/transaction.js#L73-L108) to `loopback-connector`'s [`Transaction.begin()`](https://github.com/strongloop/loopback-connector/blob/fd7d5db2c88295ed695162d906220f722a628293/lib/transaction.js#L66-L99), where it makes more sense and can be leveraged more easily by other parts of the code, e.g. the work I am doing in strongloop/loopback-datasource-juggler#1472. For a more detailed description of the motivation to do so, see …
> Part 2 of moving tx timeout and id to connector

- .npmrc
- .travis.yml
- lib/sql.js
- package.json
- test/transaction.test.js
- Drop support for Node 4.x
- Travis: add Node.js 8.x + 10.x to the build matrix
- Disable package-lock feature of npm
- Update eslint + config to latest
- Update Mocha and Chai to latest
- Update strong-globalize to 4.x
- Update msgpack5 to 4.x
> Drop support for Node.js 4.x + update dependencies

- lib/connector.js
- test/connector.test.js
Currently the `getPropertyDefinition()` method of the Connector class allows the retrieval of definitions of properties only on the very first level.
The following changes allow the retrieval of definitions for nested properties.
It correctly handles nested Objects and Arrays.
This is particularly important in the implementation of connectors, to correctly handle the coercion of conditions in the `filter` object.
Example: https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L939
> Connector.getPropertyDefinition for nested properties

- lib/connector.js
- test/connector.test.js
Keep backward-compatilibity from #136 so that for first level properties, we return what we did before.
Fixes https://github.com/strongloop/loopback-connector-postgresql/issues/364
> fix: return undefined for first level undefined props

- lib/transaction.js
- package.json
- test/transaction.test.js
Add promise support to transaction class methods.
- Connect to https://github.com/strongloop/loopback-next/issues/2614.
> chore: add promise support

- lib/sql.js
- package.json
- test/sql.test.js
Prevent adding listeners to 'connected' event past the limit established in the 
datasource.
- connect to https://github.com/strongloop/loopback-next/issues/2198
> fix: prevent adding listeners past limit

- lib/sql.js
- test/sql.test.js
When building an array of WHERE statements to join with AND, do not include empty statements.
Fixes #133
> Fix bad where

- lib/connector.js
- lib/model-key-composer.js
- lib/sql.js
- test/connector.test.js
- test/model-key-composer.test.js
- test/sql.test.js
Run `eslint --fix .` to add trailing commas to function arguments.
See also https://github.com/strongloop/loopback-connector/pull/156
/cc @brettcomardelle
> Fix eslint violations

- package.json
Configure cis-jenkins CI build to ignore the following repositories
when deciding which downstream projects to build:
- loopback-connector-db2z
- loopback-connector-informix
- loopback-connector-mqlight
- loopback-connector-kv-extreme-scale
The list is the same as we have in loopback-datasource-juggler now.
Additionally, we are removing loopback-connector-ibmi too, because we don't have any database instance to use for CI builds (yet).
- `npm test` passes on your machine
- Commit messages are following …
> chore: remove unstable connectors from downstream list

- lib/transaction.js
Break down the PR https://github.com/strongloop/loopback-connector/pull/163 into a code PR + a test PR. See the reason:
My tests fail due to a circular dependency: there is another loopback-connector installed inside node_modules in parallel with loopback-datasource-juggler and therefore loopback-datasource-juggler uses its own loopback-connector as dependency instead of my code. So I may have to release the isActive function first to get tests pass.
**This is the CODE PR**
test PR see #165 , we need to RELEASE the code PR first then merge the test.
> feat: add isactive check for transaction

- test/transaction.test.js
Break down the PR https://github.com/strongloop/loopback-connector/pull/163 into a code PR + a test PR. See the reason:
My tests fail due to a circular dependency: there is another loopback-connector installed inside node_modules in parallel with loopback-datasource-juggler and therefore loopback-datasource-juggler uses its own loopback-connector as dependency instead of my code. So I may have to release the isActive function first to get tests pass.
**This is the TEST PR**
code PR see #164 
> isactive test

- lib/transaction.js
- test/transaction.test.js
Related: strongloop-internal/scrum-apex#440
Update the copyrights year in the rest of the packages besides #4596.
The changes are introduced by running the `slt copyright` command. 
> chore: update copyright year

- lib/sql.js
- test/sql.test.js
connects to https://github.com/strongloop/loopback-next/issues/4751
LB4 allows us to have different name for model properties and column names, it can done by:
```
export class TestTable extends Entity {
@property({
type: 'number',
required: false,
scale: 0,
id: 1,
postgresql: {
columnName: 'testId', // ->set col name
dataType: 'int',
},
})
id: number;
@property({
type: 'string',
required: true,
length: 100,
postgresql: {
columnName: 'name',
dataType: 'character varying',
dataLength: 100,
},
})
testName: string;
```
In `loopback-connector`, we have 2 different functions `idColumn` and `column` to get the defined column name, the previous one is for id properties.
Idealy, `column` and `idColumn` return the column name that we defined in model definition (e.g `testId` in the above example). …
> fix how connector gets column name for id property

- lib/sql.js
- test/automigrate.test.js
Fixes https://github.com/strongloop/loopback-connector/issues/168
Replaces `async.each` with `async.eachSeries` in `automigrate()` and `autoudate()` so migrations are run in a series instead of in parallel.  This enforces the model order so foreign key constructs with Postgres are possible. 
Previously it was impossible to enforce order in Loopback 4 using the `models` option to  `migrateSchema({models: ['m1', 'm2']})` as documented here https://loopback.io/doc/en/lb4/todo-list-tutorial-sqldb.html
> fix: run migrations in series

- lib/connector.js
- lib/sql.js
- test/connectors/test-connector.js
- test/name-mapping.test.js
- test/sql.test.js
connects to https://github.com/strongloop/loopback-next/issues/4763
- push `idColumn/column` to `Connector` and rename as `idMapping/propertyMapping`
- remove idcolumn/column from SQLConnector
- remove tests relate to these two functions from sql.test.js
- create a new mock connector that is only for testing these two functions
- create a new test file name-mapping.test.js to test out new names/alias names
> push column/idcolumn to connector level

- lib/parameterized-sql.js
Fixed a problem that hangs code when, for example a param is a very large Buffer.
Fixes #161
> Fix assertion timeout logging huge parameters

- .travis.yml
- package.json
- [SEMVER-MAJOR] Drop support for Node.js 8.x, it's no longer supported by Node.js project
- travis: add Node.js 14.x
> Drop support for Node.js 8.x, start testing 14.x

- lib/sql.js
- test/sql.test.js
This is required to preserve the order of conditions:
```
where: {or: [{name: 'Top Cat'}, {address: 'Trash can'}], vip: true},
```
Before this PR:
```
WHERE (`NAME`=$1) OR (`ADDRESS`=$2) AND `VIP`=$3
```
With this PR:
```
WHERE ((`NAME`=$1) OR (`ADDRESS`=$2)) AND `VIP`=$3
```
**Need to watch downstream builds to make suer it won't break existing tests**
> Group clauses for AND/OR conditions

- .github/workflows/continuous-integration.yaml
- .travis.yml
- package.json
see: https://github.com/loopbackio/cicd/issues/2
see: https://github.com/loopbackio/cicd/issues/6
see: https://github.com/loopbackio/cicd/issues/4
> ci: update envirnoment

- lib/connector.js
- test/connector.test.js
There's inconsistent implementation on checking if a property has the "nullable" characteristic. As such, connectors (including our own) don't always (or never) utilise `Connector.isNullable()`.
This PR attempts to cover all possible flag values (for "not nullable") while keeping the liberal "default-to-nullable" logic. Hence in theory, it should be backwards compatible.
> fix: support additional values for Connector.isNullable

- .gitignore
- lib/sql.js
- test/sql.test.js
Signed-off-by: Samarpan Bhattacharya <this.is.samy@gmail.com>
1. Adds new `createAll` method to support insert multiple rows in single query
2. Adds a new flag `multiInsertSupported` to allow derived connectors to disable this feature if this SQL dialect is not supported. By default, it is false for backwards compatibility.
Fixes #227
See also https://github.com/loopbackio/loopback-next/issues/3357
> feat: add capability for insert multiple rows in single query

- lib/sql.js
Signed-off-by: Samarpan Bhattacharya <this.is.samy@gmail.com>
Fixes an issue with newly introduced createAll() method where it was not returning all ids of inserted records. The format of the data returned was also wrong. Introduced a new base function getInsertedIds() which needs to be implemented by connectors if they use multi insert support. It is similar to getInsertedId().
See also https://github.com/loopbackio/loopback-connector/issues/227 and https://github.com/loopbackio/loopback-next/issues/3357
> fix: return inserted ids with models in createAll

- lib/sql.js
- test/name-mapping.test.js
- test/sql.test.js
This PR removes the readOnly fields from the SQL query.
See also #[9339](https://github.com/loopbackio/loopback-next/pull/9339)
> fix: remove readOnly keys from query

- .github/workflows/continuous-integration.yaml
- .npmignore
- package.json
BREAKING-CHANGE: drop support for Node.js 16 and lower
> chore: drop support for Node.js 16 and lower

- lib/sql.js
Passing options to connector's buildQueryColumns function.
> feat: pass options to buildQueryColumns

- lib/sql.js
- test/connectors/test-sql-connector.js
- test/sql.test.js
Insert all only inserted properties based on the properties of the first item in the data array.
Thus, `.createAll([{firstName: 'Kyle'},{firstName:'Kyler',lastName:'Hoskins'}])` would drop the last name entirely unless it was the first item in the array
I included a new test case to highlight the use case the existing `buildFieldsFromArray` fails under.
I modified two other parts of the test files:
1. The test model was using incorrect types for middle name and last name.  This was highlighted because:
2. I added a more realistic toColumnValue based on mssql and postgres connectors, which return a value for undefined keys such that parameter numbers match
> fix: handle undefined properties in insert all

- lib/sql.js
> feat: query to fetch unique columns
